/**
 * Virtual File System (VFS) for Rob IDE
 * Manages the transition from "Meta-Blueprints" to "Real Source Code"
 */

export const createInitialWorkspace = (description, blueprint) => {
  const primaryColor = blueprint.style.primaryColor || '#7EDBFF';

  return {
    id: blueprint.id,
    name: blueprint.name,
    description: description,
    files: {
      'App.jsx': `
const App = () => {
  return (
    <div className="p-8 min-h-screen bg-white font-sans text-slate-900 border-x border-slate-100 flex flex-col items-center justify-center gap-6">
      <div className="w-16 h-16 bg-blue-50 rounded-2xl flex items-center justify-center text-blue-500">
        <Icons.Sparkles size={32} />
      </div>
      <div className="text-center space-y-2">
        <h1 className="text-2xl font-bold tracking-tight">${blueprint.name}</h1>
        <p className="text-slate-500 text-sm leading-relaxed max-w-[280px]">
          Generated by Rob The Builder. ${description}
        </p>
      </div>
      <div className="w-full max-w-[300px] h-[1px] bg-slate-100" />
      <div className="flex flex-wrap justify-center gap-2">
        ${blueprint.pages.map(p => `
        <span className="px-3 py-1 bg-slate-50 text-slate-400 text-[10px] font-bold uppercase rounded-full border border-slate-100">
          ${p.name}
        </span>`).join('')}
      </div>
    </div>
  );
};
`,
      'styles.css': `
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --brand-color: ${primaryColor};
}

body {
  cursor: default;
  -webkit-font-smoothing: antialiased;
}
`,
      'constants.js': `
export const APP_ID = "${blueprint.id}";
export const THEME_COLOR = "${primaryColor}";
`
    },
    updatedAt: new Date().toISOString()
  };
};

export const updateFile = (workspace, filename, content) => {
  return {
    ...workspace,
    files: {
      ...workspace.files,
      [filename]: content
    },
    updatedAt: new Date().toISOString()
  };
};
